# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_axi/run_vivado/constraints/soc_lite_top.xdc

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/l2_way1_tag_ram/l2_way1_tag_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==l2_way1_tag_ram || ORIG_REF_NAME==l2_way1_tag_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way1_Bank3_ram/dcache_way1_Bank3_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way1_Bank3_ram || ORIG_REF_NAME==dcache_way1_Bank3_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way1_Bank2_ram/dcache_way1_Bank2_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way1_Bank2_ram || ORIG_REF_NAME==dcache_way1_Bank2_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way1_Bank1_ram/dcache_way1_Bank1_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way1_Bank1_ram || ORIG_REF_NAME==dcache_way1_Bank1_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way1_Bank0_ram/dcache_way1_Bank0_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way1_Bank0_ram || ORIG_REF_NAME==dcache_way1_Bank0_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way0_Bank3_ram/dcache_way0_Bank3_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way0_Bank3_ram || ORIG_REF_NAME==dcache_way0_Bank3_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way0_Bank2_ram/dcache_way0_Bank2_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way0_Bank2_ram || ORIG_REF_NAME==dcache_way0_Bank2_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way0_Bank1_ram/dcache_way0_Bank1_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way0_Bank1_ram || ORIG_REF_NAME==dcache_way0_Bank1_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way0_Bank0_ram/dcache_way0_Bank0_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way0_Bank0_ram || ORIG_REF_NAME==dcache_way0_Bank0_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way1_TAGV_ram/dcache_way1_TAGV_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way1_TAGV_ram || ORIG_REF_NAME==dcache_way1_TAGV_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/dcache_way0_TAGV_ram/dcache_way0_TAGV_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dcache_way0_TAGV_ram || ORIG_REF_NAME==dcache_way0_TAGV_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way1_Bank1_ram/icache_way1_Bank1_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way1_Bank1_ram || ORIG_REF_NAME==icache_way1_Bank1_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way1_Bank0_ram/icache_way1_Bank0_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way1_Bank0_ram || ORIG_REF_NAME==icache_way1_Bank0_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way0_Bank3_ram/icache_way0_Bank3_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way0_Bank3_ram || ORIG_REF_NAME==icache_way0_Bank3_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way0_Bank2_ram/icache_way0_Bank2_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way0_Bank2_ram || ORIG_REF_NAME==icache_way0_Bank2_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way0_Bank1_ram/icache_way0_Bank1_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way0_Bank1_ram || ORIG_REF_NAME==icache_way0_Bank1_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way0_Bank0_ram/icache_way0_Bank0_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way0_Bank0_ram || ORIG_REF_NAME==icache_way0_Bank0_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way1_TAGV_ram/icache_way1_TAGV_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way1_TAGV_ram || ORIG_REF_NAME==icache_way1_TAGV_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way0_TAGV_ram/icache_way0_TAGV_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==icache_way0_TAGV_ram || ORIG_REF_NAME==icache_way0_TAGV_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/div_gen_0/div_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_0 || ORIG_REF_NAME==div_gen_0} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/mult_gen_0/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet
