# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/.Xil/Vivado-728-jyb的thinkbook/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg676-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/common
    d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/rtl/xilinx_ip/clk_pll
    d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram
  } {
      E:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/common
    d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/rtl/xilinx_ip/clk_pll
    d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/rtl/xilinx_ip/inst_ram
  } {
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/.Xil/Vivado-728-jyb的thinkbook/realtime/clk_pll_stub.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/.Xil/Vivado-728-jyb的thinkbook/realtime/data_ram_stub.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/.Xil/Vivado-728-jyb的thinkbook/realtime/inst_ram_stub.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/decode/ALU_srcGenerator.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/execute/EXE_MEM_reg.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/execute/EXEport.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/execute/ID_EXE_reg.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/decode/IDport.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/frontend/fetch/IF_ID_reg.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/frontend/fetch/IFport.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/memory/MEM_WB_reg.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/memory/MEMport.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/writeback/WBport.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/execute/alu.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/common/bram_data_stream_controller.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/rtl/BRIDGE/bridge_1x2.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/hazard/conflict_detector.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/hazard/conflict_handle.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/rtl/CONFREG/confreg.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/control/forward_deliver.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/decode/get_reg_read_addr.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/decode/imm_generator.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/decode/inst_dec.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/top/mycpu_top.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/frontend/fetch/npc.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/decode/op_dec.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/frontend/fetch/pc.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/backend/control/pipeline_controller.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/common/regfile.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/myCPU/common/tools.v
      D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/rtl/soc_lite_top.v
    }
      rt::read_vhdl -lib xpm E:/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xbip_utils_v3_0_11 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/xbip_utils_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib axi_utils_v2_0_7 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/axi_utils_v2_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_pipe_v3_0_7 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/xbip_pipe_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_wrapper_v3_0_5 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_addsub_v3_0_7 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_bram18k_v3_0_7 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/xbip_bram18k_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib mult_gen_v12_0_19 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/mult_gen_v12_0_vh_rfs.vhd
      rt::read_vhdl -lib floating_point_v7_0_21 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/floating_point_v7_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_mult_v3_0_7 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/xbip_dsp48_mult_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib xbip_dsp48_multadd_v3_0_7 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd
      rt::read_vhdl -lib div_gen_v5_1_20 d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/hdl/div_gen_v5_1_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/div_gen_0/synth/div_gen_0.vhd
      d:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/project/loongson.gen/sources_1/ip/mult_gen_0/synth/mult_gen_0.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top soc_lite_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/Loongarchcpu/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_bram/run_vivado/.Xil/Vivado-728-jyb的thinkbook/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
