# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/jtag_axi/jtag_axi.xci
# IP: The module: 'jtag_axi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/jtag_axi/gen/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/jtag_axi/gen/jtag_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/jtag_axi/jtag_axi.xci
# IP: The module: 'jtag_axi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/jtag_axi/gen/constraints/jtag_axi.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/jtag_axi/gen/jtag_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
