# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/ip_core/dcache_way1_TAGV_ram/dcache_way1_TAGV_ram.xci
# IP: The module: 'dcache_way1_TAGV_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Loongarch_cpu/output/loongson.gen/sources_1/ip/dcache_way1_TAGV_ram_1/dcache_way1_TAGV_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcache_way1_TAGV_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/ip_core/dcache_way1_TAGV_ram/dcache_way1_TAGV_ram.xci
# IP: The module: 'dcache_way1_TAGV_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Loongarch_cpu/output/loongson.gen/sources_1/ip/dcache_way1_TAGV_ram_1/dcache_way1_TAGV_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcache_way1_TAGV_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
