# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_dram/run_vivado/constraints/soc_lite_top.xdc

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_dram/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_dram/rtl/xilinx_ip/data_ram/data_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/soc_verify/soc_dram/rtl/xilinx_ip/inst_ram/inst_ram.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inst_ram || ORIG_REF_NAME==inst_ram} -quiet] -quiet
