# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_crossbar_2x3/axi_crossbar_2x3.xci
# IP: The module: 'axi_crossbar_2x3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_crossbar_2x3/gen/axi_crossbar_2x3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_2x3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_crossbar_2x3/axi_crossbar_2x3.xci
# IP: The module: 'axi_crossbar_2x3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/h546d/Desktop/zzz/chiplab/chip/soc_demo/nscscc-team/xilinx_ip/axi_crossbar_2x3/gen/axi_crossbar_2x3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_2x3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
