# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way1_Bank2_ram/icache_way1_Bank2_ram.xci
# IP: The module: 'icache_way1_Bank2_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Loongarch_cpu/output/loongson.gen/sources_1/ip/icache_way1_Bank2_ram_1/icache_way1_Bank2_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icache_way1_Bank2_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Loongarch_cpu/output/vivado_cpu_origin/myCPU/IP/icache_way1_Bank2_ram/icache_way1_Bank2_ram.xci
# IP: The module: 'icache_way1_Bank2_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Loongarch_cpu/output/loongson.gen/sources_1/ip/icache_way1_Bank2_ram_1/icache_way1_Bank2_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'icache_way1_Bank2_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
